# Numpy Important Functions

In [1]:
import numpy as np

#   

## Creating Arrays

### *1. Making an 1D Array*

In [2]:
# np.array( [list of data] , dtype)
array = np.array([1, 4, 5, 8], dtype=float)
array

array([1., 4., 5., 8.])

In [3]:
array = np.array([1, 4, 5, 8], dtype=int)
array

array([1, 4, 5, 8])

### *2. Making a 2D Array *

In [4]:
# np.array( [ [list of data], [list of data], .... ] , dtype)
array = np.array([ [1, 4, 5, 8], [2, 8, 10, 16]], dtype=float)
array

array([[ 1.,  4.,  5.,  8.],
       [ 2.,  8., 10., 16.]])

### *3. Making 3D Array*

In [5]:
# np.array( [[[list of data], [list of data]],  [[list of data], [list of data]].... ] , dtype)
array = np.array([ [[1, 4, 5, 8], [2, 8, 10, 16]], [[1, 4, 5, 8], [2, 8, 10, 16]] ] , dtype=float)
array

array([[[ 1.,  4.,  5.,  8.],
        [ 2.,  8., 10., 16.]],

       [[ 1.,  4.,  5.,  8.],
        [ 2.,  8., 10., 16.]]])

### *4. Making an array of all 0's, 1's, identitiy Matrix, Random Number*

- All below examples are for 2D arrays, similarly 3D can be made by changing size variable. For example
    - size = (2,4)   -->    2 D array
    - size = (2,3,4) -->    3 D array

In [6]:
# All zeros
# np.zeros( (shape of array), dtype )
array_zero = np.zeros((2,4), dtype=int)
print "array_zero\n================\n"
print array_zero
print ''

# np.ones( (shape of array), dtype )
array_ones = np.ones((2,4), dtype=int)
print'array_ones\n================\n'
print array_ones
print ''

# np.eye( n, dtype ), where matrix will be n*n
array_identity = np.eye(2, dtype=int)
print 'array_identity\n================\n'
print array_identity
print ''

# Random Integer array
# np.random.randint()
array_random_int = np.random.randint(low= 1, high=10, size=(2,4))
print 'array_random_int\n================\n'
print array_random_int
print ''

# Random Float array
array_random_float = np.random.uniform(low=1, high=10, size=(2,4))
print 'array_random_float\n================\n'
print array_random_float
print ''

# Random flaot array between 0 and 1
array_random_float_01 = np.random.random(size=(2,4))
print 'array_random_float_01\n================\n'
print array_random_float_01
print ''

# Example of 3 D array
# 3D array of random integers
array_random_int_3D = np.random.randint(low= 1, high=10, size=(2,2,4), dtype=int)
print 'array_random_int_3D\n================\n'
print array_random_int_3D
print ''

array_zero

[[0 0 0 0]
 [0 0 0 0]]

array_ones

[[1 1 1 1]
 [1 1 1 1]]

array_identity

[[1 0]
 [0 1]]

array_random_int

[[8 1 5 8]
 [4 3 4 7]]

array_random_float

[[1.68676345 5.75405344 6.22854117 1.02620212]
 [8.72837305 9.12843583 7.68994456 5.45371696]]

array_random_float_01

[[0.89399036 0.90703941 0.45908008 0.59364411]
 [0.87560858 0.55840455 0.02438797 0.12963877]]

array_random_int_3D

[[[9 3 6 4]
  [9 8 7 9]]

 [[1 2 4 4]
  [7 4 6 1]]]



## Traversing Arrays

In [7]:
# Using 3D int array : array_random_int_3D

print array_random_int_3D.shape
print ''
print array_random_int_3D


(2L, 2L, 4L)

[[[9 3 6 4]
  [9 8 7 9]]

 [[1 2 4 4]
  [7 4 6 1]]]


In [8]:
print "\nChoosing sub array 0"
print array_random_int_3D[0]
print "\nChoosing sub array 1"
print array_random_int_3D[1]
print '\n'

print "\nIndexing sub array 0, row 0"
print array_random_int_3D[0][0]
print "\nIndexing sub array 0, row 1"
print array_random_int_3D[0][1]
print '\n'

print "\nIndexing sub array 0, row 0, column 0"
print array_random_int_3D[0][0][0]
print "\nIndexing sub array 0, row 0, column 3"
print array_random_int_3D[0][0][3]

# Same above statements can be written as below in single braces
print "\nIndexing sub array 0, row 0, column 3 : Way 2"
print array_random_int_3D[0,0,3]

# Getting a subset of array
# We want to get [4 8][5 6], i.e. subarray-0, row-0, columnn-2 & 3 and  subarray-1, row-0, columnn-2 & 3 
print "\nIndexing sub array 0 & 1, row 0, column 2 & 3"
print array_random_int_3D[:,0,2:]

# Looping using for loop
# We want to get [3,4],[9,2],[7,5],[6,4] i.e. alternate.
# subarray-0, row-0, col-0,2
#             row-1, col-0,2
# subarray-1, row-0, col-0,2
#             row-1, col-0,2
print "\nLooping"
for i in range(2):
    for j in range(2):
        print array_random_int_3D[i,j,[0,2]]


Choosing sub array 0
[[9 3 6 4]
 [9 8 7 9]]

Choosing sub array 1
[[1 2 4 4]
 [7 4 6 1]]



Indexing sub array 0, row 0
[9 3 6 4]

Indexing sub array 0, row 1
[9 8 7 9]



Indexing sub array 0, row 0, column 0
9

Indexing sub array 0, row 0, column 3
4

Indexing sub array 0, row 0, column 3 : Way 2
4

Indexing sub array 0 & 1, row 0, column 2 & 3
[[6 4]
 [4 4]]

Looping
[9 6]
[9 7]
[1 4]
[7 6]


## Numpy Arithmetics

In [9]:
a = np.array([[1,2,3,4],[5,6,7,8]], dtype=int)
b = np.array([[9,10,11,12],[13,14,15,16]], dtype=int)

In [10]:
print 'a'
print a
print 'b'
print b
print "\n======\n"


# Scaler operation (Broadcasting)
# same applies to all 5 opertions, +, -, *, /, %

c = a
print 'Value before addition (Broadcasting)'
print c
c = a+1
print 'Value after addition a+1 (Broadcasting)'
print c
print "\n======\n"


# matrix operation, element by element
# same applies to all 5 opertions, +, -, *, /, %
c = a
print 'Value before addition (matrix operation)'
print c
c = a+b
print 'Value after addition a+b (matrix operation)'
print c
print "\n======\n"

# matrix multiplication -- dot product
try:
    c = np.dot(a,b)
except Exception as e:
    print e
# for Dot product of a and b, the size should be (n*m).(m,k) which is not the case here, so we will reshape b

print "\n reshaping b to make shape (4,2)\n"
print 'a'
print a
print 'd'
print d
print "\n======\n"
d = b.reshape(4,2)
c = np.dot(a,d)
print 'Value after dot product a.d '
print c


a
[[1 2 3 4]
 [5 6 7 8]]
b
[[ 9 10 11 12]
 [13 14 15 16]]


Value before addition (Broadcasting)
[[1 2 3 4]
 [5 6 7 8]]
Value after addition a+1 (Broadcasting)
[[2 3 4 5]
 [6 7 8 9]]


Value before addition (matrix operation)
[[1 2 3 4]
 [5 6 7 8]]
Value after addition a+b (matrix operation)
[[10 12 14 16]
 [18 20 22 24]]


shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

 reshaping b to make shape (4,2)

a
[[1 2 3 4]
 [5 6 7 8]]
d


NameError: name 'd' is not defined

## Reshaping array

In [11]:
print a
print ''
print a.shape

[[1 2 3 4]
 [5 6 7 8]]

(2L, 4L)


In [12]:
# since shape of a is (2,4) so we can reshape it in factors of 8 only. i.e 2*4, 4*2, 2*2*2
print "\nShape (8*1)"
print a.reshape(8,1)
print "\nShape (1*8)"
print a.reshape(1,8)
print "\nShape (2*2*2)"
print a.reshape(2,2,2)


Shape (8*1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

Shape (1*8)
[[1 2 3 4 5 6 7 8]]

Shape (2*2*2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### *Meaning of -1 in reshaping*
### *-1 is used if that dimension is not known*

In [26]:
# Example
array = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7])
array.shape

(16L,)

In [31]:
a = array

print 'Original array'
print a
print ''

# Reshaping to 4*4, when Order is C
a = array.reshape(4,4, order='C')
print 'array.reshape(4,4, order=\'C\'), order is C'
print a
print ''

# Reshaping to 4*4, when Order is F
a = array.reshape(4,4,order='F')
print 'array.reshape(4,4,order=\'F\'), order is F'
print a
print ''

# For all further examples, by default the order is C
print "\nFor all further examples, by default the order is C\n"

# Reshaping to 2*8
a = array.reshape(2,8)
print 'array.reshape(2,8)'
print a
print ''

# Let's say we want to reshape to 1 row, but no idea about columns
a = array.reshape(1,-1)
# Here column = -1, i.e. take row =1 , and adjust column automatically
print 'array.reshape(1,-1)'
print a
print ''

# Similarly, we want to reshape to 1 column, but no idea about rows
a = array.reshape(-1,1)
print 'array.reshape(-1,1)'
print a
print ''


# Similarly, we want to reshape to 2 column, but no idea about rows
a = array.reshape(-1,2)
print 'array.reshape(-1,2)'
print a
print ''

# and so on.
# Important : Both i.e. row and column cannot be made -1. One parameter is to be specified and other can be adjusted.
a = array.reshape(-1)
print 'array.reshape(-1)'
# Only giving one parameter i.e. -1 will convert the array to 1*n array, where n is the number of elements.
print a
print ''


Original array
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7]

array.reshape(4,4, order='C'), order is C
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [4 5 6 7]]

array.reshape(4,4,order='F'), order is F
[[1 5 9 4]
 [2 6 1 5]
 [3 7 2 6]
 [4 8 3 7]]


For all further examples, by default the order is C

array.reshape(2,8)
[[1 2 3 4 5 6 7 8]
 [9 1 2 3 4 5 6 7]]

array.reshape(1,-1)
[[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7]]

array.reshape(-1,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]

array.reshape(-1,2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 1]
 [2 3]
 [4 5]
 [6 7]]

array.reshape(-1)
[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7]

