# Numpy Important Functions

In [2]:
import numpy as np

#   

## Creating Arrays

### *1. Making an 1D Array*

In [3]:
# np.array( [list of data] , dtype)
array = np.array([1, 4, 5, 8], dtype=float)
array

array([1., 4., 5., 8.])

In [4]:
array = np.array([1, 4, 5, 8], dtype=int)
array

array([1, 4, 5, 8])

### *2. Making a 2D Array *

In [5]:
# np.array( [ [list of data], [list of data], .... ] , dtype)
array = np.array([ [1, 4, 5, 8], [2, 8, 10, 16]], dtype=float)
array

array([[ 1.,  4.,  5.,  8.],
       [ 2.,  8., 10., 16.]])

### *3. Making 3D Array*

In [29]:
# np.array( [[[list of data], [list of data]],  [[list of data], [list of data]].... ] , dtype)
array = np.array([ [[1, 4, 5, 8], [2, 8, 10, 16]], [[1, 4, 5, 8], [2, 8, 10, 16]] ] , dtype=float)
array

array([[[ 1.,  4.,  5.,  8.],
        [ 2.,  8., 10., 16.]],

       [[ 1.,  4.,  5.,  8.],
        [ 2.,  8., 10., 16.]]])

### *4. Making an array of all 0's, 1's, identitiy Matrix, Random Number*

- All below examples are for 2D arrays, similarly 3D can be made by changing size variable. For example
    - size = (2,4)   -->    2 D array
    - size = (2,3,4) -->    3 D array

In [40]:
# All zeros
# np.zeros( (shape of array), dtype )
array_zero = np.zeros((2,4), dtype=int)
print "array_zero\n================\n"
print array_zero
print ''

# np.ones( (shape of array), dtype )
array_ones = np.ones((2,4), dtype=int)
print'array_ones\n================\n'
print array_ones
print ''

# np.eye( n, dtype ), where matrix will be n*n
array_identity = np.eye(2, dtype=int)
print 'array_identity\n================\n'
print array_identity
print ''

# Random Integer array
# np.random.randint()
array_random_int = np.random.randint(low= 1, high=10, size=(2,4))
print 'array_random_int\n================\n'
print array_random_int
print ''

# Random Float array
array_random_float = np.random.uniform(low=1, high=10, size=(2,4))
print 'array_random_float\n================\n'
print array_random_float
print ''

# Random flaot array between 0 and 1
array_random_float_01 = np.random.random(size=(2,4))
print 'array_random_float_01\n================\n'
print array_random_float_01
print ''

# Example of 3 D array
# 3D array of random integers
array_random_int_3D = np.random.randint(low= 1, high=10, size=(2,2,4), dtype=int)
print 'array_random_int_3D\n================\n'
print array_random_int_3D
print ''

array_zero

[[0 0 0 0]
 [0 0 0 0]]

array_ones

[[1 1 1 1]
 [1 1 1 1]]

array_identity

[[1 0]
 [0 1]]

array_random_int

[[1 7 6 2]
 [5 6 3 1]]

array_random_float

[[8.37637221 1.7462615  5.92579649 1.18031008]
 [9.99858075 7.40270748 1.19483602 8.33297046]]

array_random_float_01

[[0.11017426 0.7265222  0.94493995 0.40313578]
 [0.64890465 0.55634249 0.4634528  0.64798374]]

array_random_int_3D

[[[3 8 4 8]
  [9 8 2 5]]

 [[7 3 5 6]
  [6 6 4 5]]]



## Traversing Arrays

In [41]:
# Using 3D int array : array_random_int_3D

print array_random_int_3D.shape
print ''
print array_random_int_3D


(2L, 2L, 4L)

[[[3 8 4 8]
  [9 8 2 5]]

 [[7 3 5 6]
  [6 6 4 5]]]


In [81]:
print "\nChoosing sub array 0"
print array_random_int_3D[0]
print "\nChoosing sub array 1"
print array_random_int_3D[1]
print '\n'

print "\nIndexing sub array 0, row 0"
print array_random_int_3D[0][0]
print "\nIndexing sub array 0, row 1"
print array_random_int_3D[0][1]
print '\n'

print "\nIndexing sub array 0, row 0, column 0"
print array_random_int_3D[0][0][0]
print "\nIndexing sub array 0, row 0, column 3"
print array_random_int_3D[0][0][3]

# Same above statements can be written as below in single braces
print "\nIndexing sub array 0, row 0, column 3 : Way 2"
print array_random_int_3D[0,0,3]

# Getting a subset of array
# We want to get [4 8][5 6], i.e. subarray-0, row-0, columnn-2 & 3 and  subarray-1, row-0, columnn-2 & 3 
print "\nIndexing sub array 0 & 1, row 0, column 2 & 3"
print array_random_int_3D[:,0,2:]

# Looping using for loop
# We want to get [3,4],[9,2],[7,5],[6,4] i.e. alternate.
# subarray-0, row-0, col-0,2
#             row-1, col-0,2
# subarray-1, row-0, col-0,2
#             row-1, col-0,2
print "\nLooping"
for i in range(2):
    for j in range(2):
        print array_random_int_3D[i,j,[0,2]]


Choosing sub array 0
[[3 8 4 8]
 [9 8 2 5]]

Choosing sub array 1
[[7 3 5 6]
 [6 6 4 5]]



Indexing sub array 0, row 0
[3 8 4 8]

Indexing sub array 0, row 1
[9 8 2 5]



Indexing sub array 0, row 0, column 0
3

Indexing sub array 0, row 0, column 3
8

Indexing sub array 0, row 0, column 3 : Way 2
8

Indexing sub array 0 & 1, row 0, column 2 & 3
[[4 8]
 [5 6]]

Looping
[3 4]
[9 2]
[7 5]
[6 4]


## Numpy Arithmetics

In [111]:
a = np.array([[1,2,3,4],[5,6,7,8]], dtype=int)
b = np.array([[9,10,11,12],[13,14,15,16]], dtype=int)

In [118]:
print 'a'
print a
print 'b'
print b
print "\n======\n"


# Scaler operation (Broadcasting)
# same applies to all 5 opertions, +, -, *, /, %

c = a
print 'Value before addition (Broadcasting)'
print c
c = a+1
print 'Value after addition a+1 (Broadcasting)'
print c
print "\n======\n"


# matrix operation, element by element
# same applies to all 5 opertions, +, -, *, /, %
c = a
print 'Value before addition (matrix operation)'
print c
c = a+b
print 'Value after addition a+b (matrix operation)'
print c
print "\n======\n"

# matrix multiplication -- dot product
try:
    c = np.dot(a,b)
except Exception as e:
    print e
# for Dot product of a and b, the size should be (n*m).(m,k) which is not the case here, so we will reshape b

print "\n reshaping b to make shape (4,2)\n"
print 'a'
print a
print 'd'
print d
print "\n======\n"
d = b.reshape(4,2)
c = np.dot(a,d)
print 'Value after dot product a.d '
print c


a
[[1 2 3 4]
 [5 6 7 8]]
b
[[ 9 10 11 12]
 [13 14 15 16]]


Value before addition (Broadcasting)
[[1 2 3 4]
 [5 6 7 8]]
Value after addition a+1 (Broadcasting)
[[2 3 4 5]
 [6 7 8 9]]


Value before addition (matrix operation)
[[1 2 3 4]
 [5 6 7 8]]
Value after addition a+b (matrix operation)
[[10 12 14 16]
 [18 20 22 24]]


shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

 reshaping b to make shape (4,2)

a
[[1 2 3 4]
 [5 6 7 8]]
d
[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


Value after dot product a.d 
[[130 140]
 [322 348]]


## Reshaping array

In [128]:
print a
print ''
print a.shape

[[1 2 3 4]
 [5 6 7 8]]

(2L, 4L)


In [130]:
# since shape of a is (2,4) so we can reshape it in factors of 8 only. i.e 2*4, 4*2, 2*2*2
print "\nShape (8*1)"
print a.reshape(8,1)
print "\nShape (1*8)"
print a.reshape(1,8)
print "\nShape (2*2*2)"
print a.reshape(2,2,2)


Shape (8*1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

Shape (1*8)
[[1 2 3 4 5 6 7 8]]

Shape (2*2*2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
